services:
 frontend:
  build:
   context: ./frontend
   dockerfile: dev.Dockerfile
  ports:
   - 3000:3000

 backend:
  build:
   context: ./backend
   dockerfile: dev.Dockerfile
  ports:
   - 3001:3001

