# Generated by Django 4.1.3 on 2022-12-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="dislikes",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="likes",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="published",
            field=models.IntegerField(),
        ),
    ]
